//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HID_Wiimote_Control_Center.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlCenter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlCenter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HID_Wiimote_Control_Center.Properties.ControlCenter", typeof(ControlCenter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Board.
        /// </summary>
        public static string ExtensionString_BalanceBoard {
            get {
                return ResourceManager.GetString("ExtensionString_BalanceBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Controller (Pro).
        /// </summary>
        public static string ExtensionString_ClassicController {
            get {
                return ResourceManager.GetString("ExtensionString_ClassicController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guitar Hero.
        /// </summary>
        public static string ExtensionString_GuitarHero {
            get {
                return ResourceManager.GetString("ExtensionString_GuitarHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiimote + Nunchuck.
        /// </summary>
        public static string ExtensionString_Nunchuck {
            get {
                return ResourceManager.GetString("ExtensionString_Nunchuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiimote.
        /// </summary>
        public static string ExtensionString_Wiimote {
            get {
                return ResourceManager.GetString("ExtensionString_Wiimote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wii U Pro Controller.
        /// </summary>
        public static string ExtensionString_WiiUProController {
            get {
                return ResourceManager.GetString("ExtensionString_WiiUProController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPad-Mouse.
        /// </summary>
        public static string ModeString_DPadMouse {
            get {
                return ResourceManager.GetString("ModeString_DPadMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamepad.
        /// </summary>
        public static string ModeString_Gamepad {
            get {
                return ResourceManager.GetString("ModeString_Gamepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamepad + IR-Mouse.
        /// </summary>
        public static string ModeString_GamepadAndIRMouse {
            get {
                return ResourceManager.GetString("ModeString_GamepadAndIRMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR-Mouse.
        /// </summary>
        public static string ModeString_IRMouse {
            get {
                return ResourceManager.GetString("ModeString_IRMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass Through.
        /// </summary>
        public static string ModeString_PassThrough {
            get {
                return ResourceManager.GetString("ModeString_PassThrough", resourceCulture);
            }
        }
    }
}
